apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  containers:
  - name: demo-container
    image: public.ecr.aws/viadee/k8s-demo-app:1.2.0
    ports:
    - containerPort: 8080
      name: http
    resources:
      limits:
        memory: 512Mi
        cpu: 1000m
      requests:
        memory: 256Mi
        cpu: 500m  
  restartPolicy: Always
